### ISSUE TITLE
Null object reference with react-native switch

### ISSUE THREAD

**Issue by mkoo21** [forcedotcom/SalesforceMobileSDK-ReactNative#14]
We are trying to upgrade our react-native app from mobile SDK version 4.3 to 5.0, but we are getting a strange issue with react-native's switch component in. We are testing on android 6, and we get the error on both the emulator and physical device.

To reproduce: Add a switch component anywhere in a new forcedroid project, or just use my index.android.js:

```
'use strict';

import React from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    ListView,
    PixelRatio,
    Navigator,
    Switch
} from 'react-native';

import {oauth, net} from 'react-native-force';

var App = React.createClass({
    getInitialState: function() {
        return {
            authenticated: false,
            value: true
        };
    },

    componentDidMount: function() {
        var that = this;
        oauth.authenticate(
            function() {
                that.setState({authenticated:true});
            },
            function(error) {
                console.log('Failed to authenticate:' + error);
            }
        );
    },

    render: function() {
        if (!this.state.authenticated)
            return (<View/>); // Show splash screen if you have one

        return (<Navigator
                  style={styles.container}
                  initialRoute={{name: 'Mobile SDK Sample App', index: 0}}
                  renderScene={(route, navigator) => (<UserList/>)}
                  navigationBar={<Navigator.NavigationBar routeMapper={NavigationBarRouteMapper} />} />);
    }
});


var NavigationBarRouteMapper = {

  LeftButton: function(route, navigator, index, navState) {
      return null;
  },

  RightButton: function(route, navigator, index, navState) {
      return null;
  },

  Title: function(route, navigator, index, navState) {
      return (
              <View style={styles.navBar}>
                <Text style={styles.navBarText}>
                  {route.name}
                </Text>
              </View>
      );
  },
};


var UserList = React.createClass({
    getInitialState: function() {
      var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
      return {
          dataSource: ds.cloneWithRows([]),
      };
    },
    
    componentDidMount: function() {
        var that = this;
        var soql = 'SELECT Id, Name FROM User LIMIT 10';
        net.query(soql,
                  function(response) {
                      var users = response.records;
                      var data = [];
                      for (var i in users) {
                          data.push(users[i]["Name"]);
                      }

                      that.setState({
                          dataSource: that.getDataSource(data),
                      });

                  });
    },

    getDataSource: function(users: Array<any>): ListViewDataSource {
        return this.state.dataSource.cloneWithRows(users);
    },

    render: function() {
        return (
            <ListView style={styles.scene}
              dataSource={this.state.dataSource}
              renderRow={this.renderRow}
              enableEmptySections={true}
            />
      );
    },

    renderRow: function(rowData: Object) {
        return (
                <View>
                    <View style={styles.row}>
                      <Text numberOfLines={1}>
                       {rowData}
                      </Text>
                    </View>
                    <Switch value={this.state.value} onChange={ (newVal) => this.setState({ value: newVal })} />
                    <View style={styles.cellBorder} />
                </View>
        );
    }
});

var styles = StyleSheet.create({
    container: {
        backgroundColor: 'white',
    },
    navBar: {
        height: 50,
        flexDirection: 'row',
        alignItems: 'center',
    },
    navBarText: {
        fontSize: 18,
    },
    scene: {
        flex: 1,
        paddingTop: 50,
    },
    row: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: 'white',
        flexDirection: 'row',
        padding: 12,
    },
    cellBorder: {
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
        // Trick to get the thinest line the device can display
        height: 1 / PixelRatio.get(),
        marginLeft: 4,
    },
});

AppRegistry.registerComponent('switchtest', () => App);
```

Expected behaviour: Render a switch in each row

Actual behaviour: 
![screen shot 2016-12-21 at 4 55 43 pm](https://cloud.githubusercontent.com/assets/12832801/21407663/b89d2392-c79e-11e6-9324-620bc96478cc.png)

Error Log: 
```
12-21 17:02:04.106  2455  2489 E unknown:React: Exception in native call
12-21 17:02:04.106  2455  2489 E unknown:React: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
12-21 17:02:04.106  2455  2489 E unknown:React: 	at android.text.StaticLayout.<init>(StaticLayout.java:420)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at android.support.v7.widget.SwitchCompat.makeLayout(SwitchCompat.java:606)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at android.support.v7.widget.SwitchCompat.onMeasure(SwitchCompat.java:526)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at android.view.View.measure(View.java:18788)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode.measure(ReactSwitchManager.java:62)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.CSSNode.measure(CSSNode.java:147)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:563)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:756)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:756)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:756)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1344)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:237)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.csslayout.CSSNode.calculateLayout(CSSNode.java:156)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:756)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:530)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:519)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:499)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.cxxbridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:92)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.cxxbridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:129)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:739)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
12-21 17:02:04.106  2455  2489 E unknown:React: 	at java.lang.Thread.run(Thread.java:818)
12-21 17:02:04.117  2455  2489 E unknown:React: Exception in native call
12-21 17:02:04.117  2455  2489 E unknown:React: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
12-21 17:02:04.117  2455  2489 E unknown:React: 	at android.text.StaticLayout.<init>(StaticLayout.java:420)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at android.support.v7.widget.SwitchCompat.makeLayout(SwitchCompat.java:606)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at android.support.v7.widget.SwitchCompat.onMeasure(SwitchCompat.java:526)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at android.view.View.measure(View.java:18788)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode.measure(ReactSwitchManager.java:62)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.CSSNode.measure(CSSNode.java:147)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:563)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:756)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:756)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:756)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1344)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1156)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:405)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:237)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.csslayout.CSSNode.calculateLayout(CSSNode.java:156)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:756)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:530)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:519)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:499)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.cxxbridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:92)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.cxxbridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:129)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:739)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
12-21 17:02:04.117  2455  2489 E unknown:React: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by ivanbogdanov** [comment]
Thank you for your feedback. I will look into this issue soon.

**Comment by ivanbogdanov** [comment]
Does it look similar to this one:
https://github.com/facebook/react-native/issues/10877
?

**Comment by mkoo21** [comment]
Not really. We're using android 6 for one, and the error logs are completely different.

The reason I posted the issue here is because the switch component works fine in our old version (mobile sdk 4.3 and RN 0.30), as well as in a fresh project generated with react-native init. But for some reason it doesn't work in a fresh project generated with forcedroid create and mobile sdk 5

**Comment by mkoo21** [comment]
For what it's worth, we are able to get around the issue by using react-native init with react 15.3.2 and RN 0.35 and manually linking the salesforce react libraries. Our container also works nicely with code push's automatic linker while forcedroid does not, so manually linking with a react-native init project is probably the better way to go for android for now

**Comment by ivanbogdanov** [comment]
Got it. I am glad you found a workaround for now. Thank you for your feedback

**Comment by jeremyeaton89** [comment]
Seeing exact same problem on RN 0.39.2 using my standard S6 Galaxy 6.0.0 API 23 when we upgraded from RN 0.34.1
