### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by martinop** [forcedotcom/SalesforceMobileSDK-ReactNative#274]
I'm having this error when I open the app on android:
![image](https://user-images.githubusercontent.com/10482079/156822123-00972239-9769-403e-b967-9a2e1b993898.png)

Maybe its because I'm not adding ```apply plugin: 'com.google.gms.google-services``` to android/app/build.gradle, but if I do that the app crashes immediately

Seems like salesforce sdk are also handling firebase...

**Comment by bhariharan** [comment]
This error occurs if your app is attempting to use a newer version of `Firebase`. Please downgrade to `20.1.0`. See my comment [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2174).

**Comment by martinop** [comment]
No, not working. I downgraded my `@react-native-firebase/messaging` from ```12.9.1``` to ```12.7.1``` (which is the compatible version with react native 0.65, because I'm using react native 0.66) and it doesnt work.

**Comment by bhariharan** [comment]
That's not the library I'm referring to, I'm referring to `firebase-messaging@20.1.0`. Check your `Gradle` dependency tree to see which version of `firebase-messaging` is being pulled in.

**Comment by martinop** [comment]
I'm using version 9.2.0 of your SDK which uses react native 0.65.0 I can't downgrade more.

**Comment by martinop** [comment]
Yes but I'm not using that library directly (that's the native library) I'm using react native firebase messaging

**Comment by bhariharan** [comment]
I understand, but it seems to be pulling in a newer version automatically. You need to `exclude` the newer version through `Gradle excludes` at the app layer.

**Comment by martinop** [comment]
I'm using now
```
    implementation('com.google.firebase:firebase-messaging') {
        version {
            strictly '20.1.0'
        }
    }

``` 

But it still crashing if I keep (apply plugin: 'com.google.gms.google-services') and throwing the red screen if I remove that line :/

😭😭

**Comment by bhariharan** [comment]
Could you post a stack trace of the crash?

**Comment by martinop** [comment]
```
03-04 18:28:30.854  6300  6369 I ReactNativeJS: Running "AmgenDetect" with {"rootTag":1}
03-04 18:28:30.885  6300  6369 E ReactNativeJS: Error: Exception in HostObject::get(propName:RNFBMessagingModule): java.lang.NoSuchMethodError: No virtual method zzh()Z in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/~~fFTiTt_un8WyKqS1PYFl5g==/com.amgen.detect-afhOfQqNPiEzR7mnIKuLmw==/base.apk!classes6.dex)
03-04 18:28:30.885  6300  6369 E ReactNativeJS: 
03-04 18:28:30.885  6300  6369 E ReactNativeJS: This error is located at:
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in Navigation (at detect/index.js:11)
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in Provider (at detect/index.js:10)
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in MainApp (at renderApplication.js:50)
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in RCTView (at View.js:32)
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in View (at AppContainer.js:92)
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in RCTView (at View.js:32)
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in View (at AppContainer.js:119)
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in AppContainer (at renderApplication.js:43)
03-04 18:28:30.885  6300  6369 E ReactNativeJS:     in AmgenDetect(RootComponent) (at renderApplication.js:60)
03-04 18:28:30.891  6300  6369 E ReactNativeJS: Error: Exception in HostObject::get(propName:RNFBMessagingModule): java.lang.NoSuchMethodError: No virtual method zzh()Z in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/~~fFTiTt_un8WyKqS1PYFl5g==/com.amgen.detect-afhOfQqNPiEzR7mnIKuLmw==/base.apk!classes6.dex)
03-04 18:28:30.891  6300  6369 E ReactNativeJS: 
03-04 18:28:30.891  6300  6369 E ReactNativeJS: This error is located at:
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in Navigation (at detect/index.js:11)
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in Provider (at detect/index.js:10)
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in MainApp (at renderApplication.js:50)
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in RCTView (at View.js:32)
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in View (at AppContainer.js:92)
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in RCTView (at View.js:32)
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in View (at AppContainer.js:119)
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in AppContainer (at renderApplication.js:43)
03-04 18:28:30.891  6300  6369 E ReactNativeJS:     in AmgenDetect(RootComponent) (at renderApplication.js:60)
03-04 18:28:30.971   297   450 D goldfish-address-space: claimShared: Ask to claim region [0x1f4000000 0x1f4928000]
03-04 18:28:30.978   297   450 D goldfish-address-space: claimShared: Ask to claim region [0x1f6154000 0x1f6a7c000]
03-04 18:28:30.987   297   450 D goldfish-address-space: claimShared: Ask to claim region [0x1f6a7c000 0x1f73a4000]
03-04 18:28:31.001  1133  1133 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3420 
03-04 18:28:31.001  1133  1133 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():2002 
03-04 18:28:31.002  1133  1133 I DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():31 Notify device unlocked.
03-04 18:28:31.102   487  1230 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
03-04 18:28:31.104  6300  6300 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10151; state: ENABLED
03-04 18:28:31.105  6300  6300 W om.amgen.detec: Accessing hidden field Landroid/widget/HorizontalScrollView;->mScroller:Landroid/widget/OverScroller; (unsupported, reflection, allowed)
03-04 18:28:31.150  6300  6300 W om.amgen.detec: Accessing hidden field Landroid/widget/ScrollView;->mScroller:Landroid/widget/OverScroller; (unsupported, reflection, allowed)
03-04 18:28:31.201  6300  6300 E unknown:FabricViewStateManager: setState called without a StateWrapper
03-04 18:28:31.237   281   370 I netd    : trafficSwapActiveStatsMap() <11.67ms>
03-04 18:28:31.239   281   370 I netd    : tetherGetStats() -> {[]} <1.44ms>
03-04 18:28:31.241   281   370 I netd    : bandwidthSetGlobalAlert(2097152) <0.16ms>
03-04 18:28:31.242   281   370 I netd    : bandwidthRemoveInterfaceQuota(eth0) <0.31ms>
03-04 18:28:31.242   281   370 I netd    : bandwidthSetInterfaceQuota(eth0, 9223372036854775807) <0.18ms>
03-04 18:28:31.253   281   370 I netd    : trafficSwapActiveStatsMap() <8.37ms>
03-04 18:28:31.254   281   370 I netd    : tetherGetStats() -> {[]} <0.17ms>
03-04 18:28:31.255   281   370 I netd    : bandwidthRemoveInterfaceQuota(eth0) <0.18ms>
03-04 18:28:31.255   281   370 I netd    : bandwidthSetInterfaceQuota(eth0, 9223372036854775807) <0.15ms>
03-04 18:28:31.262  6300  6390 D SoLoader: About to load: libimagepipeline.so
03-04 18:28:31.262  6300  6390 D SoLoader: libimagepipeline.so found on /data/data/com.amgen.detect/lib-main
03-04 18:28:31.263  6300  6390 D SoLoader: Loading lib dependencies: [liblog.so, libjnigraphics.so, libc.so, libm.so, libdl.so]
03-04 18:28:31.263  6300  6390 D SoLoader: About to load: libjnigraphics.so
03-04 18:28:31.263  6300  6390 D SoLoader: libjnigraphics.so not found on /data/data/com.amgen.detect/lib-main
03-04 18:28:31.264  6300  6390 D SoLoader: libjnigraphics.so not found on /data/app/~~fFTiTt_un8WyKqS1PYFl5g==/com.amgen.detect-afhOfQqNPiEzR7mnIKuLmw==/lib/arm64
03-04 18:28:31.264  6300  6390 D SoLoader: libjnigraphics.so not found on /vendor/lib64
03-04 18:28:31.264  6300  6390 D SoLoader: libjnigraphics.so found on /system/lib64
03-04 18:28:31.264  6300  6390 D SoLoader: libjnigraphics.so loaded implicitly
03-04 18:28:31.264  6300  6390 D SoLoader: Loaded: libjnigraphics.so
03-04 18:28:31.259  6300  6300 W FrescoIoBoundEx: type=1400 audit(0.0:126): avc: granted { execute } for path="/data/data/com.amgen.detect/lib-main/libimagepipeline.so" dev="dm-4" ino=40632 scontext=u:r:untrusted_app:s0:c151,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c151,c256,c512,c768 tclass=file app=com.amgen.detect
03-04 18:28:31.265  6300  6390 D SoLoader: Loaded: libimagepipeline.so
03-04 18:28:32.790  6300  6324 D EGL_emulation: app_time_stats: avg=82.18ms min=10.10ms max=1187.20ms count=22
03-04 18:28:32.907  6300  6369 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
03-04 18:28:32.907  6300  6369 W ReactNativeJS: Error: Exception in HostObject::get(propName:RNFBMessagingModule): java.lang.NoSuchMethodError: No virtual method zzh()Z in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/~~fFTiTt_un8WyKqS1PYFl5g==/com.amgen.detect-afhOfQqNPiEzR7mnIKuLmw==/base.apk!classes6.dex)
03-04 18:28:32.907  6300  6369 W ReactNativeJS: initialiseNativeModule@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:116714:52
03-04 18:28:32.907  6300  6369 W ReactNativeJS: getNativeModule@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:116782:34
03-04 18:28:32.907  6300  6369 W ReactNativeJS: get@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:117074:64
03-04 18:28:32.907  6300  6369 W ReactNativeJS: FirebaseMessagingModule@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:115454:39
03-04 18:28:32.907  6300  6369 W ReactNativeJS: firebaseModuleWithApp@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:117370:74
03-04 18:28:32.907  6300  6369 W ReactNativeJS: initialize$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:115149:74
03-04 18:28:32.907  6300  6369 W ReactNativeJS: tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:24385:23
03-04 18:28:32.907  6300  6369 W ReactNativeJS: invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:24555:32
03-04 18:28:32.907  6300  6369 W ReactNativeJS: tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:24385:23
03-04 18:28:32.907  6300  6369 W ReactNativeJS: invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:24457:30
03-04 18:28:32.907  6300  6369 W ReactNativeJS: http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:24487:19
03-04 18:28:32.907  6300  6369 W ReactNativeJS: tryCallTwo@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:29231:9
03-04 18:28:32.907  6300  6369 W ReactNativeJS: doResolve@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:29395:25
03-04 18:28:32.907  6300  6369 W ReactNativeJS: Promise@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:29254:14
03-04 18:28:32.907  6300  6369 W ReactNativeJS: callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:24486:33
03-04 18:28:32.907  6300  6369 W ReactNativeJS: enqueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:24491:157
03-04 18:28:32.907  6300  6369 W ReactNativeJS: http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:24506:69
03-04 18:28:32.907  6300  6369 W ReactNativeJS: initialize@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:115135:42
03-04 18:28:32.907  6300  6369 W ReactNativeJS: http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:115202:17
03-04 18:28:32.907  6300  6369 W ReactNativeJS: commitHookEffectListMount@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:16895:38
03-04 18:28:32.907  6300  6369 W ReactNativeJS: commitPassiveMountOnFiber@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:18095:44
03-04 18:28:32.907  6300  6369 W ReactNativeJS: commitPassiveMountEffects_complete@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:18060:40
03-04 18:28:32.907  6300  6369 W ReactNativeJS: commitPassiveMountEffects_begin@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:18047:47
03-04 18:28:32.908  6300  6369 W ReactNativeJS: commitPassiveMountEffects@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.amgen.detect&modulesOnly=false&runModule=true:18035:40
03-04 18:28:32.908  6300  6369 W ReactNativeJS: flushPassiveEffectsImpl@http:/
03-04 18:28:39.078   163  6333 I keystore2: keystore2::watchdog: Watchdog thread idle -> terminating. Have a great day.
03-04 18:28:39.371  1363  1363 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
03-04 18:28:40.086   153   153 I logd    : logdr: UID=2000 GID=2000 PID=6392 b tail=0 logMask=99 pid=0 start=0ns deadline=0ns
03-04 18:28:43.406  1363  1363 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.feedback.internal.IFeedbackService cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
03-04 18:28:44.373   984   984 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.scheduler.ACTION_PROXY_SCHEDULE cmp=com.google.android.gms/.chimera.PersistentInternalBoundBrokerService }
03-04 18:29:00.042   656   831 D EGL_emulation: app_time_stats: avg=3374.70ms min=14.96ms max=30234.97ms count=9
03-04 18:29:01.235   379   379 W adbd    : timeout expired while flushing socket, closing
03-04 18:29:01.949   379   379 W adbd    : timeout expired while flushing socket, closing
03-04 18:29:01.949   379   379 W adbd    : timeout expired while flushing socket, closing
03-04 18:29:01.956   379   379 W adbd    : timeout expired while flushing socket, closing
03-04 18:29:03.967   379   379 W adbd    : timeout expired while flushing socket, closing
03-04 18:29:08.794   311   311 E android.hardware.power.stats@1.0-service-mock: Failed to getEnergyData
03-04 18:29:21.772  6300  6324 D EGL_emulation: app_time_stats: avg=2721.25ms min=14.19ms max=48703.78ms count=18
03-04 18:29:33.808  1274  1274 I BgTaskExecutorImpl: Starting PERIODIC background task REFRESH_SEARCH_HISTORY.
03-04 18:29:33.842  1274  6396 W LocationOracle: getBestLocation(): no location is available
03-04 18:29:33.854   487  1246 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10102; state: DISABLED
03-04 18:29:33.854   487  1246 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10102; state: DISABLED
03-04 18:29:33.854   487  1246 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10102; state: DISABLED
03-04 18:29:33.854   487  1246 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10102; state: ENABLED
03-04 18:29:33.855   487   516 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10102; state: ENABLED
03-04 18:29:33.859   282   282 D Zygote  : Forked child process 6397
03-04 18:29:33.859   487   516 I ActivityManager: Start proc 6397:com.google.process.gapps/u0a102 for content provider {com.google.android.gsf/com.google.android.gsf.settings.GoogleSettingsProvider}
03-04 18:29:33.870   379   414 I adbd    : jdwp connection from 6397
03-04 18:29:33.876  6397  6397 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10102; state: ENABLED
03-04 18:29:33.891  6397  6397 V GraphicsEnvironment: ANGLE Developer option for 'com.google.android.gsf' set to: 'default'
03-04 18:29:33.891  6397  6397 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
03-04 18:29:33.891  6397  6397 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-04 18:29:33.892  6397  6397 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-04 18:29:33.903   487  1246 D ActivityManager: pid 1212 com.google.process.gservices  received async transactions while frozen
03-04 18:29:33.904   487  1246 D ActivityManager: sync unfroze 1212 com.google.process.gservices
03-04 18:29:33.907  6397  6397 I GoogleHttpClient: GMS http client unavailable, use old client
03-04 18:29:33.911  6397  6397 I CarUiInstaller: CarUiInstaller started for com.google.android.gsf
03-04 18:29:33.939  1274  6411 I WebViewFactory: Loading com.google.android.webview version 91.0.4472.114 (code 447211484)
03-04 18:29:33.964  1274  6411 I cr_LibraryLoader: Loaded native library version number "91.0.4472.114"
03-04 18:29:33.964  1274  6411 I cr_CachingUmaRecorder: Flushed 4 samples from 4 histograms.
03-04 18:29:33.966  1274  6415 I cr_VariationsUtils: Failed reading seed file "/data/user/0/com.google.android.googlequicksearchbox/app_webview/variations_seed_new"
03-04 18:29:33.967  1274  6415 I cr_VariationsUtils: Failed reading seed file "/data/user/0/com.google.android.googlequicksearchbox/app_webview/variations_seed"
03-04 18:29:33.967  1274  6415 I cr_VariationsUtils: Requesting new seed from IVariationsSeedServer
03-04 18:29:33.977   487  1245 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10120; state: DISABLED
03-04 18:29:33.977   487  1245 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10120; state: DISABLED
03-04 18:29:33.977   487  1245 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10120; state: DISABLED
03-04 18:29:33.977   487  1245 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10120; state: ENABLED
03-04 18:29:33.977   487   516 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10120; state: ENABLED
03-04 18:29:33.980   282   282 D Zygote  : Forked child process 6419
03-04 18:29:33.980   487   516 I ActivityManager: Start proc 6419:com.google.android.webview:webview_service/u0a120 for service {com.google.android.webview/org.chromium.android_webview.services.VariationsSeedServer}
03-04 18:29:33.989   379   414 I adbd    : jdwp connection from 6419
03-04 18:29:33.994   487  1246 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 10120; state: DISABLED
03-04 18:29:34.003  6419  6419 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10120; state: ENABLED
03-04 18:29:34.011  6419  6419 V GraphicsEnvironment: ANGLE Developer option for 'com.google.android.webview' set to: 'default'
03-04 18:29:34.011  6419  6419 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
03-04 18:29:34.012  6419  6419 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-04 18:29:34.012  6419  6419 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-04 18:29:34.026  6419  6438 I cr_VariationsUtils: Seed download job already scheduled
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper: Invalid input from icing corpus JSON flag.
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper: android.util.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 123 column 2
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at android.util.JsonReader.syntaxError(JsonReader.java:1162)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at android.util.JsonReader.checkLenient(JsonReader.java:840)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at android.util.JsonReader.nextInArray(JsonReader.java:615)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at android.util.JsonReader.peek(JsonReader.java:345)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at android.util.JsonReader.hasNext(JsonReader.java:321)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.searchbox.c.b.b.k.c(SourceFile:6)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.searchbox.c.b.b.k.<init>(SourceFile:4)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.staticplugins.searchboxroot.features.n.a.c.<init>(SourceFile:4)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.staticplugins.searchboxroot.b.a(SourceFile:14)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.staticplugins.searchboxroot.y.<init>(SourceFile:8)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.binaries.velvet.app.yy.a(SourceFile:48)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at dagger.a.e.a(SourceFile:1)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.binaries.velvet.app.yz.a(Unknown Source:2)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.binaries.velvet.app.zm.f(SourceFile:44)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.binaries.velvet.app.zm.a(SourceFile:106)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.apps.gsa.search.core.service.g.a.c.a(SourceFile:2)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.libraries.gsa.k.a.g.a(SourceFile:2)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.common.w.a.dr.a(SourceFile:1)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.common.w.a.co.run(SourceFile:4)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.common.w.a.dt.run(SourceFile:1)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.libraries.g.ab.run(SourceFile:1)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.libraries.g.n.run(SourceFile:2)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at com.google.android.libraries.g.d.run(SourceFile:2)
03-04 18:29:34.143  1274  1465 W CorpusConfigHelper:    at java.lang.Thread.run(Thread.java:920)
03-04 18:29:34.153  1274  6441 W LocationOracle: getBestLocation(): no location is available
03-04 18:29:34.184  1363  1729 I Icing   : IndexChimeraService.getServiceInterface callingPackage=com.google.android.googlequicksearchbox componentName=null serviceId=36
03-04 18:29:34.238  1363  3758 W Icing   : No valid account for uploading user actions
03-04 18:29:34.242  1363  1363 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.feedback.internal.IFeedbackService cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
03-04 18:29:34.242  1363  1363 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.feedback.internal.IFeedbackService cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
03-04 18:29:34.247  1363  3758 I Icing   : Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
03-04 18:29:34.257  1274  1463 I sb.r.PDSWriter: Updating TNG suggest bootstrap data
03-04 18:29:34.267  1363  1729 I Icing   : IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=null serviceId=30
03-04 18:29:34.269  1363  3758 W Icing   : No valid account for uploading user actions
03-04 18:29:34.274  1363  3758 I Icing   : Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
03-04 18:29:34.286  1274  1445 I sb.r.PDSWriter: Updated TNG suggest bootstrap data
03-04 18:29:49.329  1363  1363 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.feedback.internal.IFeedbackService cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
03-04 18:30:00.048   656   831 D EGL_emulation: app_time_stats: avg=600
```

**Comment by martinop** [comment]
![image](https://user-images.githubusercontent.com/10482079/156844295-2ea0598b-e862-4c4f-b394-f406808b97a7.png)

**Comment by martinop** [comment]
that's using:
```
    implementation('com.google.firebase:firebase-messaging:20.1.0') {
        force = true
    }
```
